/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.spark.sql.execution.exchange

import org.apache.spark.sql.catalyst.expressions._
import org.apache.spark.sql.catalyst.plans.physical._
import org.apache.spark.sql.catalyst.rules.Rule
import org.apache.spark.sql.execution._
import org.apache.spark.sql.internal.SQLConf

/**
 * Ensures that the [[org.apache.spark.sql.catalyst.plans.physical.Partitioning Partitioning]]
 * of input data meets the
 * [[org.apache.spark.sql.catalyst.plans.physical.Distribution Distribution]] requirements for
 * each operator by inserting [[ShuffleExchange]] Operators where required.  Also ensure that the
 * input partition ordering requirements are met.
 *
 * EnsureRequirements用来确保物理计划能够执行所需要的前提条件，包括对分区和排序逻辑的处理。
 * 在特定情形下，SparkPlan对输入数据的分布（Distribution）情况和排序（Ordering）特性有着一定的要求。
 * 例如，SortMerge类型的Join算子，要求输入数据已经按照Hash方式分区且处于有序状态。
 *
 * 如果输入数据的分布或有序性无法满足当前节点的处理逻辑，则会在物理计划中添加一些Shuffle操作或排序操作来达到要求，
 * 体现在物理算子树上就是加入Exchange节点或SortExec节点。
 * 此外，该过程还涉及依赖信息（ShuffleDependency）的创建、ShuffledRowRDD的构造等，其处理逻辑可以算是整个物理计划阶段最为复杂的部分。
 */
case class EnsureRequirements(conf: SQLConf) extends Rule[SparkPlan] {
  private def defaultNumPreShufflePartitions: Int = conf.numShufflePartitions

  private def targetPostShuffleInputSize: Long = conf.targetPostShuffleInputSize

  private def adaptiveExecutionEnabled: Boolean = conf.adaptiveExecutionEnabled

  private def minNumPostShufflePartitions: Option[Int] = {
    val minNumPostShufflePartitions = conf.minNumPostShufflePartitions
    if (minNumPostShufflePartitions > 0) Some(minNumPostShufflePartitions) else None
  }

  /**
   * Given a required distribution, returns a partitioning that satisfies that distribution.
   */
  private def createPartitioning(
      requiredDistribution: Distribution,
      numPartitions: Int): Partitioning = {
    requiredDistribution match {
      case AllTuples => SinglePartition
      case ClusteredDistribution(clustering) => HashPartitioning(clustering, numPartitions)
      case OrderedDistribution(ordering) => RangePartitioning(ordering, numPartitions)
      case dist => sys.error(s"Do not know how to satisfy distribution $dist")
    }
  }

  /**
   * Adds [[ExchangeCoordinator]] to [[ShuffleExchange]]s if adaptive query execution is enabled
   * and partitioning schemes of these [[ShuffleExchange]]s support [[ExchangeCoordinator]].
   */
  private def withExchangeCoordinator(
      children: Seq[SparkPlan],
      requiredChildDistributions: Seq[Distribution]): Seq[SparkPlan] = {
    val supportsCoordinator =
      if (children.exists(_.isInstanceOf[ShuffleExchange])) {
        // Right now, ExchangeCoordinator only support HashPartitionings.
        // 子节点存在ShuffleExchange，且所有节点的输出分区方式都是HashPartitioning
        children.forall {
          case e @ ShuffleExchange(hash: HashPartitioning, _, _) => true // 子节点是HashPartitioning
          case child =>
            child.outputPartitioning match { // 子节点的输出分区分布是HashPartitioning
              case hash: HashPartitioning => true
              case collection: PartitioningCollection =>
                collection.partitionings.forall(_.isInstanceOf[HashPartitioning])
              case _ => false
            }
        }
      } else {
        // In this case, although we do not have Exchange operators, we may still need to
        // shuffle data when we have more than one children because data generated by
        // these children may not be partitioned in the same way.
        // Please see the comment in withCoordinator for more details.
        /**
         * 在这种情况下，虽然我们没有Exchange算子，但当我们有多个子节点时，我们可能仍然需要对数据进行shuffle，
         * 因为这些子节点生成的数据可能不会以相同的方式进行分区。
         * 这种情况简化为条件：子节点数目大于1且每个子节点输出数据的分布都是ClusteredDistribution类型。
         */
        val supportsDistribution =
          requiredChildDistributions.forall(_.isInstanceOf[ClusteredDistribution])
        children.length > 1 && supportsDistribution
      }

    val withCoordinator =
      if (adaptiveExecutionEnabled && // spark.sql.adaptive.enabled
        supportsCoordinator) {
        // 创建ExchangeCoordinator
        val coordinator =
          new ExchangeCoordinator(
            children.length,
            targetPostShuffleInputSize, // spark.sql.adaptive.shuffle.targetPostShuffleInputSize，默认64 * 1024 * 1024，即64M
            minNumPostShufflePartitions) // spark.sql.adaptive.minNumPostShufflePartitions，默认-1，即为None
        children.zip(requiredChildDistributions).map {
          case (e: ShuffleExchange, _) =>
            // This child is an Exchange, we need to add the coordinator.
            e.copy(coordinator = Some(coordinator))
          case (child, distribution) =>
            // If this child is not an Exchange, we need to add an Exchange for now.
            // Ideally, we can try to avoid this Exchange. However, when we reach here,
            // there are at least two children operators (because if there is a single child
            // and we can avoid Exchange, supportsCoordinator will be false and we
            // will not reach here.). Although we can make two children have the same number of
            // post-shuffle partitions. Their numbers of pre-shuffle partitions may be different.
            // For example, let's say we have the following plan
            //         Join
            //         /  \
            //       Agg  Exchange
            //       /      \
            //    Exchange  t2
            //      /
            //     t1
            // In this case, because a post-shuffle partition can include multiple pre-shuffle
            // partitions, a HashPartitioning will not be strictly partitioned by the hashcodes
            // after shuffle. So, even we can use the child Exchange operator of the Join to
            // have a number of post-shuffle partitions that matches the number of partitions of
            // Agg, we cannot say these two children are partitioned in the same way.
            // Here is another case
            //         Join
            //         /  \
            //       Agg1  Agg2
            //       /      \
            //   Exchange1  Exchange2
            //       /       \
            //      t1       t2
            // In this case, two Aggs shuffle data with the same column of the join condition.
            // After we use ExchangeCoordinator, these two Aggs may not be partitioned in the same
            // way. Let's say that Agg1 and Agg2 both have 5 pre-shuffle partitions and 2
            // post-shuffle partitions. It is possible that Agg1 fetches those pre-shuffle
            // partitions by using a partitionStartIndices [0, 3]. However, Agg2 may fetch its
            // pre-shuffle partitions by using another partitionStartIndices [0, 4].
            // So, Agg1 and Agg2 are actually not co-partitioned.
            //
            // It will be great to introduce a new Partitioning to represent the post-shuffle
            // partitions when one post-shuffle partition includes multiple pre-shuffle partitions.

            // 如果这个子节点不是Exchange，我们现在需要添加一个Exchange。
            // 理想情况下，我们可以尽量避免这种交流。
            // 但是，当我们到达这里时，至少有两个子操作符（因为如果有一个子操作符，我们可以避免Exchange，则supportsCoordinator将为false，我们将无法到达这里。）。
            // 虽然我们可以让两个子节点拥有相同数量的post-shuffle分区。它们的预混洗分区的数量可能不同。
            // 例如，假设我们有以下计划：
            //         Join
            //         /  \
            //       Agg  Exchange
            //       /      \
            //    Exchange  t2
            //      /
            //     t1
            //
            // 在这种情况下，因为一个post-shuffle分区可以包含多个pre-shuffle分区，一个HashPartitioning不会被shuffle后的hashcode严格分区。
            // 所以，即使我们可以使用Join的子交换算子来拥有多个与Agg的分区数相匹配的post-shuffle分区，我们也不能说这两个子分区的方式相同。
            // 这是另一个案例：
            //         Join
            //         /  \
            //       Agg1  Agg2
            //       /      \
            //   Exchange1  Exchange2
            //       /       \
            //      t1       t2
            //
            // 在这种情况下，两个 Aggs 使用相同的连接条件列打乱数据。
            // 我们使用ExchangeCoordinator后，这两个Agg的分区方式可能不一样。
            // 假设 Agg1 和 Agg2 都有 5 个 pre-shuffle 分区和 2 个 post-shuffle 分区。
            // Agg1 可能通过使用 partitionStartIndices [0, 3] 来获取那些预混洗分区。
            // 然而，Agg2 可以通过使用另一个 partitionStartIndices [0, 4] 来获取它的 pre-shuffle 分区。
            // 所以，Agg1 和 Agg2 实际上不是共同分区的。


            // 当一个 post-shuffle 分区包含多个 pre-shuffle 分区时，引入一个新的 Partitioning 来表示 post-shuffle 分区会很棒。
            val targetPartitioning =
              createPartitioning(distribution, defaultNumPreShufflePartitions)
            assert(targetPartitioning.isInstanceOf[HashPartitioning])
            ShuffleExchange(targetPartitioning, child, Some(coordinator))
        }
      } else {
        // If we do not need ExchangeCoordinator, the original children are returned.
        children
      }

    withCoordinator
  }

  private def ensureDistributionAndOrdering(operator: SparkPlan): SparkPlan = {
    // 取得Distribution和Ordering
    val requiredChildDistributions: Seq[Distribution] = operator.requiredChildDistribution
    val requiredChildOrderings: Seq[Seq[SortOrder]] = operator.requiredChildOrdering

    // 取得子Plan节点
    var children: Seq[SparkPlan] = operator.children

    // 子节点的Distribution和Ordering要和自己一直
    assert(requiredChildDistributions.length == children.length)
    assert(requiredChildOrderings.length == children.length)

    /**
     * Ensure that the operator's children satisfy their output distribution requirements:
     *
     * （1）添加Exchange节点第1阶段：判断每个子节点的分区方式是否可以满足（Satisfies）对应所需的数据分布。
     *  - 如果满足，则不需要创建Exchange节点。
     *  - 否则根据是否广播来决定添加何种类型的Exchange节点。
     */
    children = children.zip(requiredChildDistributions).map {
      // 子节点的分区可以满足所需的数据分布，直接返回子分区
      case (child, distribution) if child.outputPartitioning.satisfies(distribution) =>
        child
      // 数据分布是BroadcastDistribution，创建BroadcastExchangeExec
      case (child, BroadcastDistribution(mode)) => // 广播 => BroadcastExchangeExec
        BroadcastExchangeExec(mode, child)
      // 其他数据分布，创建ShuffleExchange
      case (child, distribution) => // Shuffle -> ShuffleExchange
        /**
         * defaultNumPreShufflePartitions决定了Shuffle操作过程中分区的数目，是一个可配置的参数（spark.sql.shuffle.partitions），默认为200。
         * createPartitioning方法会根据数据分布与分区数目创建对应的分区方式，具体的对应关系是：
         *  - AllTuples对应SinglePartition
         *  - ClusteredDistribution对应HashPartitioning
         *  - OrderedDistribution对应RangePartitioning
         *  - 其他情况无法对应得到分区方式，抛出RuntimeException。
         */
        ShuffleExchange(createPartitioning(distribution, defaultNumPreShufflePartitions), child)
    }

    // If the operator has multiple children and specifies child output distributions (e.g. join),
    // then the children's output partitionings must be compatible:
    def requireCompatiblePartitioning(distribution: Distribution): Boolean = distribution match {
      case UnspecifiedDistribution => false
      case BroadcastDistribution(_) => false
      case _ => true
    }

    /**
     * （1）添加Exchange节点第2阶段：针对多个子节点的情形
     * 如果当前SparkPlan节点需要所有子节点分区方式兼容但并不能满足时，就需要创建ShuffleExchange节点。
     */
    if (children.length > 1
        && requiredChildDistributions.exists(requireCompatiblePartitioning) // 子节点不存在UnspecifiedDistribution和BroadcastDistribution
        && !Partitioning.allCompatible(children.map(_.outputPartitioning))) { // 子节点存在输出分区不兼容

      // First check if the existing partitions of the children all match. This means they are
      // partitioned by the same partitioning into the same number of partitions. In that case,
      // don't try to make them match `defaultPartitions`, just use the existing partitioning.
      /**
       * 首先检查子节点的分区是否兼容，这意味着它们是被相同的Partitioning分为相同数量的分区，
       * 在这种情况下，不需要使子分区兼容默认分区，直接使用各自的Partitioning即可。
       */
      // 最大子节点分区数
      val maxChildrenNumPartitions = children.map(_.outputPartitioning.numPartitions).max
      // 判断是否直接使用各自的Partitioning
      val useExistingPartitioning = children.zip(requiredChildDistributions).forall {
        case (child, distribution) =>
          child.outputPartitioning.guarantees(
            createPartitioning(distribution, maxChildrenNumPartitions))
      }

      children = if (useExistingPartitioning) { // 直接使用各自的Partitioning，返回children即可
        // We do not need to shuffle any child's output.
        children
      } else {
        // We need to shuffle at least one child's output.
        // Now, we will determine the number of partitions that will be used by created
        // partitioning schemes.
        /**
         * 需要在至少一个子节点的输出上做Shuffle，
         * 我们需要决定用于创建Partitioning的分区数
         */
        val numPartitions = {
          // Let's see if we need to shuffle all child's outputs when we use
          // maxChildrenNumPartitions.
          /**
           * 判断在使用最大子节点分区数时，是否需要对所有子节点的输出做Shuffle
           */
          val shufflesAllChildren = children.zip(requiredChildDistributions).forall {
            case (child, distribution) =>
              !child.outputPartitioning.guarantees(
                createPartitioning(distribution, maxChildrenNumPartitions))
          }
          // If we need to shuffle all children, we use defaultNumPreShufflePartitions as the
          // number of partitions. Otherwise, we use maxChildrenNumPartitions.
          /**
           * 如果需要对所有的子节点进行Shuffle，则采用默认分区数，即spark.sql.shuffle.partitions决定的，默认200，
           * 否则使用最大子节点分区数
           */
          if (shufflesAllChildren) defaultNumPreShufflePartitions else maxChildrenNumPartitions
        }

        // 创建ShuffleExchange
        children.zip(requiredChildDistributions).map {
          case (child, distribution) =>
            val targetPartitioning = createPartitioning(distribution, numPartitions)
            if (child.outputPartitioning.guarantees(targetPartitioning)) {
              child
            } else {
              child match {
                // If child is an exchange, we replace it with
                // a new one having targetPartitioning.
                /**
                 * 根据创建的Partitioning对当前SparkPlan节点进行操作。
                 * 因为在第一个阶段针对单个子节点进行处理时有可能已经创建了ShuffleExchange节点，那么这种情况下会对其进行替换，
                 * 其他情况下直接创建新的ShuffleExchange节点即可。
                 */
                case ShuffleExchange(_, c, _) => ShuffleExchange(targetPartitioning, c)
                case _ => ShuffleExchange(targetPartitioning, child)
              }
          }
        }
      }
    }

    // （2）应用ExchangeCoordinator协调分区
    // Now, we need to add ExchangeCoordinator if necessary.
    // Actually, it is not a good idea to add ExchangeCoordinators while we are adding Exchanges.
    // However, with the way that we plan the query, we do not have a place where we have a
    // global picture of all shuffle dependencies of a post-shuffle stage. So, we add coordinator
    // at here for now.
    // Once we finish https://issues.apache.org/jira/browse/SPARK-10665,
    // we can first add Exchanges and then add coordinator once we have a DAG of query fragments.
    /**
     * ExchangeCoordinator用来确定物理计划生成的Stage之间如何进行Shuffle的行为。
     * 其作用在于协助ShuffleExchange节点“更好地”执行。
     * 在Spark 2.1版本中，ExchangeCoordinator的功能比较简单，仅用于确定数据Shuffle后（Post-shuffle）的分区数目。
     */
    children = withExchangeCoordinator(children, requiredChildDistributions)

    // （3）添加SortExec节点
    // Now that we've performed any necessary shuffles, add sorts to guarantee output orderings:
    children = children.zip(requiredChildOrderings).map { case (child, requiredOrdering) =>
      if (requiredOrdering.nonEmpty) {
        // If child.outputOrdering is [a, b] and requiredOrdering is [a], we do not need to sort.
        // 当且仅当所有子节点的输出数据的排序信息满足当前节点所需时，才不需要添加SortExec节点；否则，需要在当前节点上添加SortExec为父节点。
        val orderingMatched = if (requiredOrdering.length > child.outputOrdering.length) {
          false
        } else {
          requiredOrdering.zip(child.outputOrdering).forall {
            case (requiredOrder, childOutputOrder) =>
              requiredOrder.semanticEquals(childOutputOrder)
          }
        }

        if (!orderingMatched) {
          SortExec(requiredOrdering, global = false, child = child)
        } else {
          child
        }
      } else {
        child
      }
    }

    operator.withNewChildren(children)
  }

  def apply(plan: SparkPlan): SparkPlan = plan.transformUp {
    // 当匹配到Exchange节点（ShuffleExchange）且其子节点也是Exchange类型时，会检查两者的Partitioning方式，判断能否消除多余的Exchange节点。
    case operator @ ShuffleExchange(partitioning, child, _) =>
      child.children match {
        case ShuffleExchange(childPartitioning, baseChild, _)::Nil =>
          if (childPartitioning.guarantees(partitioning)) child else operator
        case _ => operator
      }
    // 逐个调用ensureDistributionAndOrdering方法来确保每个节点的分区与排序需求。
    case operator: SparkPlan => ensureDistributionAndOrdering(operator)
  }
}
